import { AppError } from "./errors.ts";

const retrySafeCodes = new Set([
  "ADB_ERROR",
  "APPIUM_UNAVAILABLE",
  "AUTOMATION_PREFLIGHT_FAILED",
  "APP_NOT_INSTALLED",
  "DEVICE_BUSY",
  "DEVICE_IDENTITY_MISMATCH",
  "DEVICE_NOT_CONNECTED",
  "DEVICE_OUTCOME_UNKNOWN",
  "DEVICE_PROFILE_REQUIRED",
  "ELEMENT_TIMEOUT",
  "FACEBOOK_NOT_INSTALLED",
  "FACEBOOK_TARGET_NOT_VERIFIED",
  "IDEMPOTENT_OPERATION_FAILED",
  "OPERATION_CANCELLED",
  "SETUP_REQUIRED",
  "TIKTOK_NOT_INSTALLED",
  "TIKTOK_TARGET_NOT_VERIFIED",
  "UNEXPECTED_FOREGROUND_APP",
]);

export function isAutomationRetrySafe(error: unknown) {
  return error instanceof AppError && retrySafeCodes.has(error.code);
}
